begin;
set local search_path = public, extensions;
select plan(37);

select has_table('public','vinculos_evaluacion_ejercicio','Existe tabla de vínculos');
select has_table('public','calificaciones_directas','Existe tabla de notas directas');
select has_table('public','eventos_participacion','Existe ledger de participación');
select has_view('public','vista_fuentes_calificacion','Existe read model de fuentes');
select has_view('public','vista_participacion_normalizada','Existe read model de participación');
select has_column('public','resultados_ejercicios','inscripcion_alumno_id','Resultado enlaza inscripción');
select has_column('public','resultados_ejercicios','vinculo_evaluacion_id','Resultado enlaza fuente');
select has_column('public','resultados_ejercicios','unidad_origen_id','Resultado conserva unidad');
select has_column('public','resultados_ejercicios','origen','Resultado conserva origen');
select has_column('public','resultados_ejercicios','observacion','Resultado admite observación');
select has_column('public','resultados_ejercicios','calificado_por','Resultado conserva actor');
select has_column('public','resultados_ejercicios','calificado_at','Resultado conserva fecha');
select has_column('public','resultados_ejercicios','row_version','Resultado tiene versión optimista');
select has_column('public','resultados_ejercicios','idempotency_key','Resultado tiene idempotencia');
select col_type_is('public','resultados_ejercicios','calificacion','numeric(6,4)','Nota canónica usa precisión 6,4');
select col_type_is('public','calificaciones_directas','calificacion','numeric(6,4)','Nota directa usa precisión 6,4');
select col_type_is('public','eventos_participacion','puntos','numeric(10,8)','Participación usa precisión 10,8');
select col_type_is('public','vinculos_evaluacion_ejercicio','created_at','timestamp with time zone','Fechas usan timestamptz');
select col_type_is('public','resultados_ejercicios','row_version','bigint','Versión es bigint');
select col_type_is('public','calificaciones_directas','idempotency_key','uuid','Idempotencia es UUID');
select has_index('public','vinculos_evaluacion_ejercicio','vinculos_evaluacion_assignment_period_idx','Índice asignación-periodo');
select has_index('public','vinculos_evaluacion_ejercicio','vinculos_evaluacion_exercise_idx','Índice ejercicio');
select has_index('public','resultados_ejercicios','resultados_student_idx','Índice alumno');
select has_index('public','calificaciones_directas','calificaciones_directas_assignment_period_idx','Índice notas por asignación-periodo');
select has_index('public','eventos_participacion','eventos_participacion_student_idx','Índice eventos por alumno');
select has_fk('public','vinculos_evaluacion_ejercicio','Vínculo tiene FKs');
select has_fk('public','calificaciones_directas','Nota directa tiene FKs');
select has_fk('public','eventos_participacion','Evento tiene FKs');
select has_check('public','resultados_ejercicios','Resultado controla estado/nota');
select has_check('public','calificaciones_directas','Nota directa controla estado/nota');
select has_check('public','eventos_participacion','Evento controla puntos/configuración');
select is((select relrowsecurity from pg_class where oid='public.resultados_ejercicios'::regclass),true,'RLS en resultados');
select is((select relrowsecurity from pg_class where oid='public.vinculos_evaluacion_ejercicio'::regclass),true,'RLS en vínculos');
select is((select relrowsecurity from pg_class where oid='public.calificaciones_directas'::regclass),true,'RLS en directas');
select is((select relrowsecurity from pg_class where oid='public.eventos_participacion'::regclass),true,'RLS en participación');
select is((select reloptions @> array['security_invoker=true'] from pg_class where oid='public.vista_fuentes_calificacion'::regclass),true,'Vista fuentes usa invocador');
select is((select reloptions @> array['security_invoker=true'] from pg_class where oid='public.vista_participacion_normalizada'::regclass),true,'Vista participación usa invocador');

select * from finish();
rollback;
