'use client';

import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { submitFamilyRegistration } from '@/lib/actions/filter-family-public';
import { clearFamilyRegistrationDraft, getFamilyRegistrationDraft, persistFile, restoreFile, saveFamilyRegistrationDraft } from '@/lib/filter-early-departure-draft';
import { FilterEvidenceCapture } from './FilterEvidenceCapture';
import { FilterSignaturePad } from './FilterSignaturePad';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Person = { fullName: string; relationship: string; phone: string; identificationReference: string };
const FILE_KEYS = ['identificationFront','identificationBack','facePhoto','signature'] as const;

export function FamilyRegistrationForm({ token, context }: { token: string; context: any }) {
  const scope = token.slice(0, 24); const [requestId, setRequestId] = useState('');
  const [values, setValues] = useState<Record<string, string | boolean>>({ guardianName: '', relationship: '', relationshipOther: '', phone: '', email: '', identificationReference: '', privacyConsent: false });
  const [people, setPeople] = useState<Person[]>([]); const [files, setFiles] = useState<Record<string, File | null>>({ identificationFront: null, identificationBack: null, facePhoto: null, signature: null });
  const [personFiles, setPersonFiles] = useState<Record<string, File | null>>({}); const [ready, setReady] = useState(false); const [saving, setSaving] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState('');
  const allFiles = useMemo(() => ({ ...files, ...personFiles }), [files, personFiles]);
  useEffect(() => { getFamilyRegistrationDraft(scope).then((draft) => { if (draft) { setRequestId(draft.clientRequestId); setValues(draft.values); setPeople(draft.people as Person[]); const restored = Object.fromEntries(Object.entries(draft.files).map(([key,value]) => [key, restoreFile(value)])); setFiles((old) => ({ ...old, ...Object.fromEntries(Object.entries(restored).filter(([key]) => FILE_KEYS.includes(key as any))) })); setPersonFiles(Object.fromEntries(Object.entries(restored).filter(([key]) => !FILE_KEYS.includes(key as any)))); } else setRequestId(crypto.randomUUID()); }).finally(() => setReady(true)); }, [scope]);
  useEffect(() => { if (!ready || !requestId || done) return; const timer = setTimeout(() => void saveFamilyRegistrationDraft(scope, { version: 1, clientRequestId: requestId, values, people, files: Object.fromEntries(Object.entries(allFiles).map(([key,file]) => [key, persistFile(file)])), updatedAt: new Date().toISOString() }), 300); return () => clearTimeout(timer); }, [allFiles, done, people, ready, requestId, scope, values]);
  const update = (key: string, value: string | boolean) => setValues((old) => ({ ...old, [key]: value }));
  const submit = async () => { setError(''); if (!files.identificationFront || !files.facePhoto || !files.signature || values.privacyConsent !== true) return setError('Completa las evidencias, firma y consentimiento obligatorios.'); if (people.some((_, i) => !personFiles[`authorizedPhoto${i}`])) return setError('Falta la fotografía de una persona autorizada.'); setSaving(true); const body = new FormData(); body.set('clientRequestId', requestId); Object.entries(values).forEach(([k,v]) => body.set(k, String(v))); body.set('authorizedPeople', JSON.stringify(people)); Object.entries(allFiles).forEach(([k,v]) => { if (v) body.set(k, v); }); try { const result = await submitFamilyRegistration(token, body); if (!result.success) return setError(result.error || 'No se pudo enviar. El borrador permanece intacto.'); await clearFamilyRegistrationDraft(scope); setDone(true); } catch { setError('No hay conexión con el servidor. Conservamos todo en este dispositivo; vuelve a pulsar Enviar cuando regrese internet.'); } finally { setSaving(false); } };
  if (done) return <Card className="mx-auto max-w-2xl"><CardContent className="p-10 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-primary" /><h1 className="mt-4 text-2xl font-bold">Registro recibido</h1><p className="mt-2 text-muted-foreground">El plantel revisará la identidad y la vinculación antes de habilitar a las personas autorizadas.</p></CardContent></Card>;
  return <main className="min-h-screen bg-muted/30 p-4 sm:p-8"><Card className="mx-auto max-w-3xl"><CardHeader className="text-center">{context.logoUrl && <img src={context.logoUrl} alt="Logotipo institucional" className="mx-auto h-20 w-20 object-contain" />}<CardTitle className="text-2xl">Registro seguro de familia</CardTitle><p className="font-semibold text-primary">{context.institutionName}</p><p className="text-sm">Alumno: {context.studentName} · {context.academic}</p></CardHeader><CardContent className="space-y-6">
    <Alert><ShieldCheck className="h-4 w-4" /><AlertTitle>Enlace individual y privado</AlertTitle><AlertDescription>No busques al alumno: el enlace ya está vinculado exclusivamente a su expediente. Los datos quedan pendientes de revisión por el plantel.</AlertDescription></Alert>
    <section className="grid gap-4 sm:grid-cols-2"><Field label="Nombre completo"><Input value={String(values.guardianName)} onChange={(e) => update('guardianName', e.target.value)} /></Field><Field label="Parentesco"><Select value={String(values.relationship)} onValueChange={(v) => update('relationship', v)}><SelectTrigger><SelectValue placeholder="Selecciona" /></SelectTrigger><SelectContent><SelectItem value="madre">Madre</SelectItem><SelectItem value="padre">Padre</SelectItem><SelectItem value="tutor">Tutor(a)</SelectItem><SelectItem value="otro">Otro</SelectItem></SelectContent></Select></Field>{values.relationship === 'otro' && <Field label="Especifica parentesco"><Input value={String(values.relationshipOther)} onChange={(e) => update('relationshipOther', e.target.value)} /></Field>}<Field label="Teléfono"><Input inputMode="tel" value={String(values.phone)} onChange={(e) => update('phone', e.target.value)} /></Field><Field label="Correo (opcional)"><Input type="email" value={String(values.email)} onChange={(e) => update('email', e.target.value)} /></Field><Field label="Últimos caracteres de identificación"><Input maxLength={12} value={String(values.identificationReference)} onChange={(e) => update('identificationReference', e.target.value)} /></Field></section>
    <FilterEvidenceCapture label="Identificación oficial (frente)" help="Fotografía o PDF legible." file={files.identificationFront} onChange={(file) => setFiles((o) => ({ ...o, identificationFront: file }))} allowPdf /><FilterEvidenceCapture label="Identificación oficial (reverso, opcional)" help="Sólo cuando corresponda." file={files.identificationBack} onChange={(file) => setFiles((o) => ({ ...o, identificationBack: file }))} allowPdf required={false} /><FilterEvidenceCapture label="Fotografía actual del padre, madre o tutor" help="Servirá para la consulta visual privada del personal autorizado." file={files.facePhoto} onChange={(file) => setFiles((o) => ({ ...o, facePhoto: file }))} guide="adult" /><FilterSignaturePad label="Firma de consentimiento" help="Firma con el dedo, lápiz digital o mouse." file={files.signature} onChange={(file) => setFiles((o) => ({ ...o, signature: file }))} />
    <section className="space-y-4 rounded-xl border p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Otras personas autorizadas</h2><p className="text-sm text-muted-foreground">Opcional, máximo cinco. Cada una quedará pendiente de validación.</p></div><Button type="button" variant="outline" disabled={people.length >= 5} onClick={() => setPeople((old) => [...old, { fullName:'',relationship:'',phone:'',identificationReference:'' }])}><Plus className="mr-2 h-4 w-4" />Agregar</Button></div>{people.map((person,index) => <div key={index} className="space-y-3 rounded-lg bg-muted/40 p-4"><div className="flex justify-end"><Button size="sm" variant="ghost" onClick={() => { setPeople((old) => old.filter((_,i) => i !== index)); setPersonFiles({}); }}><Trash2 className="h-4 w-4" /></Button></div><div className="grid gap-3 sm:grid-cols-2">{(['fullName','relationship','phone','identificationReference'] as const).map((key) => <Field key={key} label={{fullName:'Nombre completo',relationship:'Parentesco',phone:'Teléfono',identificationReference:'Referencia de identificación'}[key]}><Input maxLength={key === 'identificationReference' ? 12 : undefined} value={person[key]} onChange={(e) => setPeople((old) => old.map((p,i) => i === index ? {...p,[key]:e.target.value} : p))} /></Field>)}</div><FilterEvidenceCapture label="Fotografía actual" help="Obligatoria para identificación visual." file={personFiles[`authorizedPhoto${index}`] || null} onChange={(file) => setPersonFiles((o) => ({ ...o, [`authorizedPhoto${index}`]: file }))} guide="adult" /><FilterEvidenceCapture label="Identificación (opcional)" help="Fotografía o PDF." file={personFiles[`authorizedId${index}`] || null} onChange={(file) => setPersonFiles((o) => ({ ...o, [`authorizedId${index}`]: file }))} allowPdf required={false} /></div>)}</section>
    <label className="flex items-start gap-3 rounded-xl border-2 border-primary/30 p-4"><Checkbox checked={values.privacyConsent === true} onCheckedChange={(v) => update('privacyConsent', v === true)} /><span className="text-sm">Confirmo que la información es verdadera y autorizo al plantel a usar estos datos y fotografías exclusivamente para seguridad, vinculación familiar y entrega del alumno.</span></label>
    {error && <Alert variant="destructive"><AlertTitle>No se pudo continuar</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<div className="flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground"><Save className="mr-1 inline h-3 w-3" />El borrador, incluidas fotografías, se conserva localmente en este dispositivo.</p><Button size="lg" disabled={saving || !ready} onClick={submit}>{saving ? 'Enviando…' : 'Enviar a revisión'}</Button></div>
  </CardContent></Card></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
