'use client';

import { useMemo, useState } from 'react';
import { Download, FileText, Search } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { getFilterReportPackets } from '@/lib/actions/filter-control';
import { normalizeFilterName } from '@/lib/filter-control';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Selection = { type: 'early'|'extraordinary'; id: string };
export function FilterReports({ initialData }: { initialData:any }) {
  const {toast}=useToast(); const [query,setQuery]=useState(''); const [type,setType]=useState('all'); const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState(false);
  const rows=useMemo(()=>[...initialData.early.map((r:any)=>({...r,_type:'early'})),...initialData.extraordinary.map((r:any)=>({...r,_type:'extraordinary'}))].filter((r:any)=>(type==='all'||r._type===type)&&normalizeFilterName(r.student_name).includes(normalizeFilterName(query))).sort((a:any,b:any)=>String(b.registered_at).localeCompare(String(a.registered_at))),[initialData,type,query]);
  const key=(r:any)=>`${r._type}:${r.id}`; const exportPdf=async(explicit?:Selection[])=>{const targets:Selection[]=explicit || rows.filter((r:any)=>selected.includes(key(r))).map((r:any)=>({type:r._type,id:r.id}));if(!targets.length)return;setBusy(true);try{for(let offset=0;offset<targets.length;offset+=40){const result=await getFilterReportPackets(targets.slice(offset,offset+40));if(!result.success)throw new Error(result.error);const packetRows=[...(result.early||[]).map((r:any)=>({...r,_type:'early'})),...(result.extraordinary||[]).map((r:any)=>({...r,_type:'extraordinary'}))];const doc=new jsPDF();for(let i=0;i<packetRows.length;i++){if(i)doc.addPage();await drawRecord(doc,packetRows[i],result.institution,result.urls);}doc.save(`bitacoras-filtro${targets.length>40?`-parte-${offset/40+1}`:''}.pdf`);}toast({title:'PDF generado',description:`${targets.length} expediente(s) exportados.`});}catch(e){toast({variant:'destructive',title:'No se pudo generar el PDF',description:e instanceof Error?e.message:'Error inesperado'});}finally{setBusy(false);}};
  return <div className="space-y-6"><div><h1 className="flex items-center gap-2 text-3xl font-bold text-primary"><FileText />Reportes de entregas</h1><p className="text-muted-foreground">Consulta, selecciona e imprime salidas anticipadas y entregas extraordinarias con sus evidencias.</p></div><Card><CardHeader><CardTitle>Expedientes</CardTitle><CardDescription>Por protección de datos, cada exportación queda registrada en auditoría. Los lotes grandes se separan automáticamente.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_220px_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por alumno"/></div><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Ambas bitácoras</SelectItem><SelectItem value="early">Salidas anticipadas</SelectItem><SelectItem value="extraordinary">Entregas extraordinarias</SelectItem></SelectContent></Select><Button disabled={busy||!selected.length} onClick={() => void exportPdf()}><Download className="mr-2 h-4 w-4"/>{busy?'Preparando…':`Descargar ${selected.length}`}</Button></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={rows.length>0&&rows.every((r:any)=>selected.includes(key(r)))} onCheckedChange={v=>setSelected(v?rows.map(key):[])}/>Seleccionar todos los resultados visibles</label><div className="space-y-2">{rows.map((r:any)=><label key={key(r)} className="flex items-center gap-3 rounded-lg border p-3 hover:bg-muted/40"><Checkbox checked={selected.includes(key(r))} onCheckedChange={v=>setSelected(s=>v?[...new Set([...s,key(r)])]:s.filter(x=>x!==key(r)))}/><span className="flex-1"><b>{r.student_name}</b><span className="block text-xs text-muted-foreground">{r._type==='early'?'Salida anticipada':'Entrega extraordinaria'} · {new Date(r.registered_at).toLocaleString('es-MX')} · {r.reporter_name}</span></span><Button type="button" size="sm" variant="outline" onClick={e=>{e.preventDefault();void exportPdf([{type:r._type,id:r.id}])}}>PDF</Button></label>)}</div></CardContent></Card></div>;
}
async function dataUrl(url?:string){if(!url)return null;try{const blob=await fetch(url).then(r=>r.blob());return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});}catch{return null;}}
async function drawRecord(doc:jsPDF,row:any,institution:any,urls:Record<string,string>){const color=hex(institution.color_primario||'#0f766e');doc.setFillColor(...color);doc.rect(0,0,210,24,'F');doc.setTextColor(255,255,255);doc.setFontSize(16);doc.text(institution.nombre_completo||institution.nombre_corto||'Institución',14,11);doc.setFontSize(9);doc.text('EXPEDIENTE CONFIDENCIAL · CONTROL DE FILTRO',14,18);doc.setTextColor(20,20,30);doc.setFontSize(15);doc.text(row._type==='early'?'Bitácora de salida anticipada':'Entrega a persona extraordinaria',14,36);const fields=row._type==='early'?[['Alumno',row.student_name],['Nivel / grado / grupo',`${row.level_name} · ${row.grade_name} · ${row.group_name}`],['Fecha y hora',fmt(row.departed_at)],['Persona que retira',row.pickup_person_name],['Parentesco',row.relationship],['Identificación',row.identification_type],['Notificación',`${row.notified_person_type} · ${row.notification_method}`],['Motivo',row.reason_code],['Entrega',row.delivering_teacher_name],['Registra',row.reporter_name],['Observaciones',row.description]]:[['Alumno',row.student_name],['Nivel / grado / grupo',`${row.level_name} · ${row.grade_name} · ${row.group_name}`],['Fecha y hora',fmt(row.departed_at||row.registered_at)],['Persona que retira',row.pickup_person_name],['Relación',row.pickup_relationship],['Autoriza',`${row.authorizer_name} · ${row.authorization_method}`],['Validación',`${row.identity_status} · ${row.consent_status}`],['Resolución',row.status],['Entrega',row.delivering_teacher_name],['Registra',row.reporter_name],['Observaciones',row.final_observations]];let y=45;doc.setFontSize(9);for(const [label,value] of fields){doc.setFont('helvetica','bold');doc.text(`${label}:`,14,y);doc.setFont('helvetica','normal');const lines=doc.splitTextToSize(String(value||'—'),145);doc.text(lines,50,y);y+=Math.max(7,lines.length*5);}const images=row._type==='early'?[['Persona',row.pickup_person_photo_path],['Entrega final',row.final_handover_photo_path],['Firma',row.pickup_signature_path]]:[['Persona',row.pickup_person_photo_path],['Vehículo',row.vehicle_photo_path],['Entrega final',row.final_handover_photo_path],['Firma',row.pickup_signature_path]];for(const [label,path] of images){if(!path||!urls[path])continue;const image=await dataUrl(urls[path]);if(!image)continue;if(y>235){doc.addPage();y=20;}doc.setFont('helvetica','bold');doc.text(label,14,y);try{doc.addImage(image,'JPEG',14,y+3,65,48,undefined,'FAST');}catch{try{doc.addImage(image,'PNG',14,y+3,65,48,undefined,'FAST');}catch{continue;}}y+=57;}doc.setFontSize(7);doc.setTextColor(100);doc.text(`Folio ${row.id} · Generado ${new Date().toLocaleString('es-MX')} · Página ${doc.getNumberOfPages()}`,14,290);}
function fmt(v:string){return v?new Date(v).toLocaleString('es-MX'):'—';} function hex(value:string):[number,number,number]{const v=value.replace('#','');return v.length===6?[parseInt(v.slice(0,2),16),parseInt(v.slice(2,4),16),parseInt(v.slice(4,6),16)]:[15,118,110];}
