'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, CheckCircle2, Clock3, CloudOff, FileText, Plus, Search, TimerReset, UserRoundPlus } from 'lucide-react';
import { addFilterStudents, createLateEntry, getFilterEvidenceUrl, getStudentLateAlert, searchFilterReporters, searchFilterStudents } from '@/lib/actions/filter-control';
import { FILTER_REASONS } from '@/lib/filter-control';
import { clearLateEntryDraft, getLateEntryDraft, persistFile, restoreFile, saveLateEntryDraft } from '@/lib/filter-early-departure-draft';
import { useToast } from '@/hooks/use-toast';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';
import { FilterEvidenceCapture } from './FilterEvidenceCapture';

export function FilterLateLog({ initialData, initialClock }: { initialData: any; initialClock: any }) {
  const router = useRouter(); const { toast } = useToast(); const [transitioning, startTransition] = useTransition();
  const scope = useMemo(() => `${initialData.tenantId}:${initialData.actorUserId}`, [initialData.tenantId, initialData.actorUserId]);
  const [studentQuery, setStudentQuery] = useState(''); const [studentResults, setStudentResults] = useState<any[]>([]); const [student, setStudent] = useState<any>(null); const [lateAlert, setLateAlert] = useState<any>(null);
  const [reason, setReason] = useState('trafico'); const [reasonDetail, setReasonDetail] = useState(''); const [automaticTime, setAutomaticTime] = useState(true); const [arrivedAt, setArrivedAt] = useState('');
  const [reporter, setReporter] = useState(initialData.isGeneral ? '' : initialData.actorName); const [reporterResults, setReporterResults] = useState<any[]>([]);
  const [addOpen, setAddOpen] = useState(false); const [newName, setNewName] = useState(''); const [newGroup, setNewGroup] = useState(initialData.groups[0]?.id || '');
  const [clockNow, setClockNow] = useState(() => initialClock.iso ? new Date(initialClock.iso) : new Date()); const [evidence, setEvidence] = useState<File | null>(null);
  const [requestId, setRequestId] = useState(''); const [hydrated, setHydrated] = useState(false); const [storageSafe, setStorageSafe] = useState(true); const [draftStatus, setDraftStatus] = useState<'draft'|'queued'>('draft'); const [savedAt, setSavedAt] = useState(''); const [online, setOnline] = useState(true); const [sending, setSending] = useState(false);

  useEffect(() => { const timer = setInterval(() => setClockNow((current) => new Date(current.getTime() + 1000)), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { setOnline(navigator.onLine); const up = () => setOnline(true); const down = () => setOnline(false); window.addEventListener('online', up); window.addEventListener('offline', down); return () => { window.removeEventListener('online', up); window.removeEventListener('offline', down); }; }, []);
  useEffect(() => {
    void getLateEntryDraft(scope).then((draft) => {
      if (draft) {
        setRequestId(draft.clientRequestId); setDraftStatus(draft.status); setStudent(draft.student); setStudentQuery(draft.values.studentQuery);
        setReason(draft.values.reason); setReasonDetail(draft.values.reasonDetail); setAutomaticTime(draft.values.automaticTime); setArrivedAt(draft.values.arrivedAt); setReporter(draft.values.reporter); setEvidence(restoreFile(draft.evidence)); setSavedAt(draft.updatedAt);
        if (draft.student?.id) void getStudentLateAlert(String(draft.student.id)).then(setLateAlert);
      } else setRequestId(crypto.randomUUID());
    }).catch(() => setStorageSafe(false)).finally(() => setHydrated(true));
  }, [scope]);
  const currentDraft = useCallback((status: 'draft'|'queued' = draftStatus) => ({ version: 1 as const, clientRequestId: requestId, status, updatedAt: new Date().toISOString(), student, values: { studentQuery, reason, reasonDetail, automaticTime, arrivedAt, reporter }, evidence: persistFile(evidence) }), [requestId, draftStatus, student, studentQuery, reason, reasonDetail, automaticTime, arrivedAt, reporter, evidence]);
  useEffect(() => { if (!hydrated || !requestId) return; const timer = setTimeout(() => { void saveLateEntryDraft(scope, currentDraft()).then(() => { setStorageSafe(true); setSavedAt(new Date().toISOString()); }).catch(() => setStorageSafe(false)); }, 120); return () => clearTimeout(timer); }, [hydrated, requestId, scope, currentDraft]);
  useEffect(() => { const preserve = () => { if (hydrated && requestId) void saveLateEntryDraft(scope, currentDraft()); }; const visibility = () => { if (document.visibilityState === 'hidden') preserve(); }; window.addEventListener('pagehide', preserve); document.addEventListener('visibilitychange', visibility); return () => { window.removeEventListener('pagehide', preserve); document.removeEventListener('visibilitychange', visibility); }; }, [hydrated, requestId, scope, currentDraft]);
  useEffect(() => { const timer = setTimeout(async () => { if (studentQuery.trim().length < 2 || student?.full_name === studentQuery) return setStudentResults([]); const result = await searchFilterStudents(studentQuery); if (result.success) setStudentResults(result.data); }, 250); return () => clearTimeout(timer); }, [studentQuery, student]);
  useEffect(() => { if (!initialData.isGeneral) return; const timer = setTimeout(async () => { if (reporter.trim().length < 1) return setReporterResults([]); const result = await searchFilterReporters(reporter); if (result.success) setReporterResults(result.data); }, 250); return () => clearTimeout(timer); }, [reporter, initialData.isGeneral]);

  const chooseStudent = async (selected: any) => { setStudent(selected); setStudentQuery(selected.full_name); setStudentResults([]); setLateAlert(await getStudentLateAlert(selected.id)); };
  const resetAfterSuccess = useCallback(async () => { await clearLateEntryDraft(scope); setStudent(null); setStudentQuery(''); setLateAlert(null); setReason('trafico'); setReasonDetail(''); setAutomaticTime(true); setArrivedAt(''); setEvidence(null); setDraftStatus('draft'); setSavedAt(''); setRequestId(crypto.randomUUID()); if (initialData.isGeneral) setReporter(''); router.refresh(); }, [scope, initialData.isGeneral, router]);
  const send = useCallback(async () => {
    if (!student?.id || !requestId || sending) return;
    if (!navigator.onLine) { setDraftStatus('queued'); await saveLateEntryDraft(scope, currentDraft('queued')).catch(() => setStorageSafe(false)); toast({ title: 'Registro protegido sin conexión', description: 'Se enviará automáticamente cuando vuelva internet.' }); return; }
    setSending(true);
    try {
      const form = new FormData(); form.set('clientRequestId', requestId); form.set('studentId', String(student.id)); form.set('automaticTime', String(automaticTime)); form.set('arrivedAt', arrivedAt); form.set('reasonCode', reason); form.set('reasonDetail', reasonDetail); form.set('reporterName', reporter); if (evidence) form.set('evidence', evidence);
      const result = await createLateEntry(form);
      if (!result.success) { setDraftStatus('draft'); toast({ variant: 'destructive', title: 'No se guardó el retardo', description: `${result.error} El borrador y su evidencia siguen protegidos en este dispositivo.` }); return; }
      toast({ title: result.duplicate ? 'El retardo ya estaba guardado' : 'Retardo registrado y auditado' }); await resetAfterSuccess();
    } catch { setDraftStatus('queued'); await saveLateEntryDraft(scope, currentDraft('queued')).catch(() => setStorageSafe(false)); toast({ title: 'Envío pendiente', description: 'La conexión se interrumpió; no se perdió nada y se reintentará automáticamente.' }); }
    finally { setSending(false); }
  }, [student, requestId, sending, scope, currentDraft, automaticTime, arrivedAt, reason, reasonDetail, reporter, evidence, toast, resetAfterSuccess]);
  useEffect(() => { if (online && hydrated && draftStatus === 'queued' && student?.id && !sending) void send(); }, [online, hydrated, draftStatus, student, sending, send]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void send(); };
  const addStudent = () => startTransition(async () => { const result = await addFilterStudents({ groupId: newGroup, names: [newName] }); if (!result.success) toast({ variant: 'destructive', title: 'No se agregó', description: result.error }); else { toast({ title: 'Alumno agregado' }); setAddOpen(false); setNewName(''); router.refresh(); } });
  const openEvidence = async (path: string) => { const result = await getFilterEvidenceUrl(path); if (result.success && result.url) window.open(result.url, '_blank', 'noopener,noreferrer'); else toast({ variant: 'destructive', title: 'No se pudo abrir', description: result.error }); };
  const groupLabel = (group: any) => { const level = initialData.levels.find((item: any) => item.id === group.level_id); return `${level?.name || 'Nivel'} · ${group.grade_name} · ${group.group_name}`; };

  return <div className="space-y-6">
    <div><h1 className="flex items-center gap-2 text-3xl font-bold text-primary"><TimerReset />Bitácora de retardos</h1><p className="text-muted-foreground">Registro móvil y de escritorio, atribuido y aislado para esta institución.</p></div>
    <Alert variant={!storageSafe ? 'destructive' : 'default'}>{!online ? <CloudOff className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}<AlertTitle>{!storageSafe ? 'El navegador bloqueó el almacenamiento local' : draftStatus === 'queued' ? 'Envío pendiente y protegido' : 'Borrador protegido en este dispositivo'}</AlertTitle><AlertDescription>{!storageSafe ? 'No cierres esta pestaña hasta guardar. En Safari, evita la navegación privada y permite almacenamiento del sitio.' : !online ? 'Puedes continuar: texto y evidencia se enviarán cuando regrese internet.' : savedAt ? `Guardado localmente ${new Date(savedAt).toLocaleTimeString('es-MX')}. Puedes recargar, bloquear o cerrar y volver a esta pantalla.` : 'Los datos y la evidencia se conservan automáticamente.'}</AlertDescription></Alert>
    <div className="grid gap-6 xl:grid-cols-3">
      <Card className="xl:col-span-2"><CardHeader><CardTitle>Nuevo registro</CardTitle><CardDescription>Busca al alumno incluso por nombre o cualquiera de sus apellidos.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-5">
        <div className="relative"><Label>Nombre del alumno *</Label><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={studentQuery} onChange={(e) => { setStudentQuery(e.target.value); setStudent(null); }} autoComplete="off" placeholder="Escribe nombre o apellido" />{studentResults.length > 0 && <div className="absolute z-30 mt-1 w-full rounded-md border bg-popover p-1 shadow-xl">{studentResults.map((item) => <button type="button" key={item.id} onClick={() => void chooseStudent(item)} className="block w-full rounded px-3 py-2 text-left text-sm hover:bg-muted">{item.full_name}</button>)}</div>}</div><Button type="button" variant="outline" size="icon" aria-label="Dar de alta alumno" onClick={() => setAddOpen(true)}><UserRoundPlus className="h-4 w-4" /></Button></div></div>
        {student && <div className="rounded-lg border border-primary/20 bg-primary/5 p-3"><p className="font-semibold">{student.full_name}</p></div>}
        {lateAlert?.success && <Alert variant={lateAlert.alert ? 'destructive' : 'default'}><AlertTriangle className="h-4 w-4" /><AlertTitle>{lateAlert.count} retardo(s) en el periodo configurado</AlertTitle><AlertDescription>{lateAlert.alert ? `Alerta activa: se alcanzó el límite de ${lateAlert.settings?.threshold}.` : `Aún no alcanza el umbral de ${lateAlert.settings?.threshold || 3}.`}</AlertDescription></Alert>}
        <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><div className="flex items-center justify-between"><Label>Hora de llegada *</Label><div className="flex items-center gap-2 text-xs"><span>Automática</span><Switch checked={automaticTime} onCheckedChange={setAutomaticTime} /></div></div>{automaticTime ? <div className="flex min-h-10 items-center gap-2 rounded-md border bg-muted/30 px-3 text-sm"><Clock3 className="h-4 w-4 text-primary" />{initialClock.success ? new Intl.DateTimeFormat('es-MX', { timeZone: initialClock.timezone, dateStyle: 'medium', timeStyle: 'medium' }).format(clockNow) : 'Hora del servidor al guardar'}</div> : <Input value={arrivedAt} onChange={(event) => setArrivedAt(event.target.value)} type="datetime-local" required />}{initialClock.timezone && <p className="text-xs text-muted-foreground">Zona: {initialClock.timezone}</p>}</div><div><Label>Motivo *</Label><Select value={reason} onValueChange={setReason}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{FILTER_REASONS.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div></div>
        <div><Label>{reason === 'otro' ? 'Especifica el motivo *' : 'Detalles del motivo (opcional)'}</Label><Textarea value={reasonDetail} onChange={(event) => setReasonDetail(event.target.value)} required={reason === 'otro'} rows={3} placeholder="Describe información útil del retardo" /></div>
        <FilterEvidenceCapture label="Foto o comprobante" help="Fotografía optimizada para iPad o PDF de hasta 1.5 MB. Se conserva en este dispositivo hasta confirmar el registro." file={evidence} onChange={setEvidence} allowPdf required={false} />
        <div className="relative"><Label>Nombre de quien registra {initialData.isGeneral ? '*' : ''}</Label><Input value={reporter} onChange={(e) => setReporter(e.target.value)} disabled={!initialData.isGeneral} autoComplete="off" required={initialData.isGeneral} />{reporterResults.length > 0 && <div className="absolute z-30 mt-1 w-full rounded-md border bg-popover p-1 shadow-xl">{reporterResults.map((item) => <button type="button" key={item.id} onClick={() => { setReporter(item.name); setReporterResults([]); }} className="block w-full rounded px-3 py-2 text-left text-sm hover:bg-muted">{item.name}</button>)}</div>}</div>
        <Button type="submit" size="lg" disabled={!hydrated || sending || !student || (initialData.isGeneral && reporter.trim().length < 2)}>{sending ? 'Guardando…' : !online ? 'Guardar al recuperar conexión' : 'Guardar retardo'}</Button>
      </form></CardContent></Card>
      <Card><CardHeader><CardTitle>Estado del servicio</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">Usuario autenticado</p><p className="font-semibold">{initialData.actorName}</p></div><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">Modalidad</p><p className="font-semibold">{initialData.isGeneral ? 'Encargado general' : 'Encargado individual'}</p></div><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">Alumnos disponibles</p><p className="text-2xl font-bold text-primary">{initialData.students.length}</p></div></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Registros recientes</CardTitle><CardDescription>Últimos 100 eventos compartidos por el equipo.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>Fecha y hora</TableHead><TableHead>Alumno</TableHead><TableHead>Motivo</TableHead><TableHead>Registró</TableHead><TableHead>Evidencia</TableHead></TableRow></TableHeader><TableBody>{initialData.recent.map((entry: any) => <TableRow key={entry.id}><TableCell>{new Intl.DateTimeFormat('es-MX', { dateStyle: 'short', timeStyle: 'short', timeZone: initialClock.timezone || 'America/Mexico_City' }).format(new Date(entry.arrived_at))}</TableCell><TableCell className="font-medium">{entry.filter_students?.full_name}</TableCell><TableCell><Badge variant="outline">{FILTER_REASONS.find((item) => item.value === entry.reason_code)?.label || entry.reason_code}</Badge>{entry.reason_detail && <p className="mt-1 max-w-xs text-xs text-muted-foreground">{entry.reason_detail}</p>}</TableCell><TableCell>{entry.reporter_name}</TableCell><TableCell>{entry.evidence_path ? <Button size="sm" variant="outline" onClick={() => void openEvidence(entry.evidence_path)}><FileText className="mr-2 h-4 w-4" />Abrir</Button> : '—'}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Alta rápida de alumno</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Nombre completo</Label><Input value={newName} onChange={(e) => setNewName(e.target.value)} /></div><div><Label>Nivel, grado y grupo</Label><Select value={newGroup} onValueChange={setNewGroup}><SelectTrigger><SelectValue placeholder="Selecciona grupo" /></SelectTrigger><SelectContent>{initialData.groups.map((group: any) => <SelectItem key={group.id} value={group.id}>{groupLabel(group)}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={() => setAddOpen(false)}>Cancelar</Button><Button disabled={transitioning || newName.trim().length < 2 || !newGroup} onClick={addStudent}><Plus className="mr-2 h-4 w-4" />Agregar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
