'use client';

import { useState, useTransition } from 'react';
import QRCode from 'qrcode';
import { CheckCircle2, Copy, Download, Link2, Search, ShieldCheck, UserRoundCheck, XCircle } from 'lucide-react';
import { createFamilyRegistrationInvite, reviewFamilyRegistration } from '@/lib/actions/filter-control';
import { normalizeFilterName } from '@/lib/filter-control';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

export function FilterFamilies({ initialData }: { initialData: any }) {
  const { toast } = useToast(); const [pending, start] = useTransition(); const [query, setQuery] = useState(''); const [selectedStudent, setSelectedStudent] = useState(initialData.students[0]?.id || ''); const [notes, setNotes] = useState<Record<string,string>>({}); const [targets, setTargets] = useState<Record<string,string>>({});
  const smart = (name: string) => { const q = normalizeFilterName(query); const n = normalizeFilterName(name); return !q || q.split(' ').every((word) => n.includes(word) || n.split(' ').some((part) => levenshtein(word, part) <= 2)); };
  const students = initialData.students.filter((student: any) => smart(student.full_name));
  const selected = initialData.students.find((student: any) => student.id === selectedStudent);
  const createLink = () => start(async () => { const result = await createFamilyRegistrationInvite(selectedStudent); if (!result.success || !result.path) { toast({ variant:'destructive', title:'No se pudo crear el enlace', description:result.error }); return; } const url = `${window.location.origin}${result.path}`; await navigator.clipboard.writeText(url); const dataUrl = await QRCode.toDataURL(url, { width: 900, margin: 2 }); const a = document.createElement('a'); a.href = dataUrl; a.download = `registro-familiar-${normalizeFilterName(selected?.full_name || 'alumno').replace(/ /g,'-')}.png`; a.click(); toast({ title:'Enlace copiado y QR descargado', description:`Vence ${new Date(result.expiresAt!).toLocaleString('es-MX')}. El anterior quedó revocado.` }); });
  const review = (id: string, status: 'approved'|'rejected'|'duplicate') => start(async () => { const result = await reviewFamilyRegistration({ registrationId:id, status, notes:notes[id], studentId:targets[id] }); if (!result.success) { toast({variant:'destructive',title:'No se pudo guardar',description:result.error}); return; } toast({title:'Revisión guardada y auditada'}); window.location.reload(); });
  const registrationsFor = selectedStudent ? initialData.registrations.filter((r:any) => r.student_id === selectedStudent) : [];
  return <div className="space-y-6"><div><h1 className="flex items-center gap-2 text-3xl font-bold text-primary"><UserRoundCheck />Familias y personas autorizadas</h1><p className="text-muted-foreground">Genera enlaces privados, revisa documentos y consulta rostros antes de entregar a un alumno.</p></div>
    {initialData.canIssueInvites && <Card><CardHeader><CardTitle>Compartir registro por enlace o QR</CardTitle><CardDescription>El QR queda vinculado a un solo alumno, vence en 14 días, permite un envío y revoca el enlace anterior.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-[1fr_auto]"><Select value={selectedStudent} onValueChange={setSelectedStudent}><SelectTrigger><SelectValue placeholder="Selecciona alumno" /></SelectTrigger><SelectContent>{initialData.students.map((s:any) => <SelectItem key={s.id} value={s.id}>{s.full_name}</SelectItem>)}</SelectContent></Select><Button disabled={pending || !selectedStudent} onClick={createLink}><Link2 className="mr-2 h-4 w-4" />Crear, copiar y descargar QR</Button></CardContent></Card>}
    <Card><CardHeader><CardTitle>Consulta visual privada</CardTitle><CardDescription>Disponible únicamente para personal de filtro autorizado. Busca por cualquier parte del nombre, incluso con pequeños errores.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Nombre o apellidos del alumno" /></div><div className="grid gap-2 md:grid-cols-2">{students.slice(0,40).map((student:any) => <button key={student.id} onClick={() => setSelectedStudent(student.id)} className={`rounded-lg border p-3 text-left ${student.id === selectedStudent ? 'border-primary bg-primary/5' : 'hover:bg-muted'}`}><b>{student.full_name}</b><span className="block text-xs text-muted-foreground">{academic(initialData,student)}</span></button>)}</div>
      {selected && <div className="space-y-4 rounded-xl border p-4"><h2 className="text-xl font-bold">{selected.full_name}</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{initialData.contacts.filter((c:any) => c.student_id === selected.id && c.verification_status === 'verified').map((contact:any) => { const reg = initialData.registrations.find((r:any) => r.id === contact.external_registration_id); return <Person key={contact.id} title={contact.full_name} subtitle={`${contact.relationship} · contacto oficial`} url={reg && initialData.urls[reg.face_photo_path]} verified />; })}{initialData.people.filter((p:any) => p.student_id === selected.id && p.verification_status === 'verified').map((person:any) => <Person key={person.id} title={person.full_name} subtitle={`${person.relationship} · autorizado`} url={initialData.urls[person.face_photo_path]} verified />)}</div>{!initialData.contacts.some((c:any) => c.student_id === selected.id && c.verification_status === 'verified') && !initialData.people.some((p:any) => p.student_id === selected.id && p.verification_status === 'verified') && <p className="text-sm text-muted-foreground">Aún no hay personas verificadas para este alumno.</p>}</div>}
    </CardContent></Card>
    {initialData.canManage && <Card><CardHeader><CardTitle>Solicitudes pendientes y correcciones</CardTitle><CardDescription>Aprobar habilita al contacto y a sus autorizados. También puedes corregir una vinculación duplicada seleccionando al alumno correcto.</CardDescription></CardHeader><CardContent className="space-y-4">{initialData.registrations.map((r:any) => <div key={r.id} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>{r.guardian_name}</b><p className="text-sm text-muted-foreground">Para {initialData.students.find((s:any) => s.id === r.student_id)?.full_name} · {r.relationship} · {r.phone}</p></div><Badge>{r.status}</Badge></div><div className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><Person title="Rostro registrado" subtitle="Identidad declarada" url={initialData.urls[r.face_photo_path]} /><div className="flex flex-wrap gap-2 text-sm"><a className="text-primary underline" target="_blank" rel="noreferrer" href={initialData.urls[r.identification_front_path]}>Ver identificación</a><a className="text-primary underline" target="_blank" rel="noreferrer" href={initialData.urls[r.signature_path]}>Ver firma</a></div></div><div className="space-y-3"><Label>Alumno correcto</Label><Select value={targets[r.id] || r.student_id} onValueChange={(v) => setTargets((o) => ({...o,[r.id]:v}))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{initialData.students.map((s:any) => <SelectItem key={s.id} value={s.id}>{s.full_name}</SelectItem>)}</SelectContent></Select><Label>Notas de revisión</Label><Textarea value={notes[r.id] || ''} onChange={(e) => setNotes((o) => ({...o,[r.id]:e.target.value}))} /></div></div><div className="flex flex-wrap gap-2"><Button disabled={pending} onClick={() => review(r.id,'approved')}><CheckCircle2 className="mr-2 h-4 w-4" />Aprobar y vincular</Button><Button variant="destructive" disabled={pending} onClick={() => review(r.id,'rejected')}><XCircle className="mr-2 h-4 w-4" />Rechazar</Button><Button variant="outline" disabled={pending} onClick={() => review(r.id,'duplicate')}><Copy className="mr-2 h-4 w-4" />Marcar duplicada</Button></div></div>)}{!initialData.registrations.length && <p className="text-muted-foreground">No hay solicitudes pendientes.</p>}</CardContent></Card>}
  </div>;
}
function Person({title,subtitle,url,verified=false}:{title:string;subtitle:string;url?:string;verified?:boolean}) { return <div className="overflow-hidden rounded-xl border bg-card"><div className="aspect-[4/3] bg-muted">{url ? <img src={url} alt={`Rostro de ${title}`} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-muted-foreground">Sin fotografía aprobada</div>}</div><div className="p-3"><p className="font-semibold">{title}</p><p className="text-xs text-muted-foreground">{subtitle}</p>{verified && <Badge className="mt-2"><ShieldCheck className="mr-1 h-3 w-3" />Verificado</Badge>}</div></div>; }
function academic(data:any, student:any) { const group=data.groups.find((g:any)=>g.id===student.group_id); const level=data.levels.find((l:any)=>l.id===group?.level_id); return group ? `${level?.name || ''} · ${group.grade_name} · Grupo ${group.group_name}` : 'Sin grupo'; }
function levenshtein(a:string,b:string){const m=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=m[0];m[0]=i;for(let j=1;j<=b.length;j++){const old=m[j];m[j]=Math.min(m[j]+1,m[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old;}}return m[b.length];}
