'use client';

import { useMemo, useState } from 'react';
import { Download, FileText, Search } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { getFilterReportPackets } from '@/lib/actions/filter-control';
import { normalizeFilterName } from '@/lib/filter-control';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Selection = { type: 'early'|'extraordinary'; id: string };
export function FilterReports({ initialData }: { initialData:any }) {
  const {toast}=useToast(); const [query,setQuery]=useState(''); const [type,setType]=useState('all'); const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState(false);
  const rows=useMemo(()=>[...initialData.early.map((r:any)=>({...r,_type:'early'})),...initialData.extraordinary.map((r:any)=>({...r,_type:'extraordinary'}))].filter((r:any)=>(type==='all'||r._type===type)&&normalizeFilterName(r.student_name).includes(normalizeFilterName(query))).sort((a:any,b:any)=>String(b.registered_at).localeCompare(String(a.registered_at))),[initialData,type,query]);
  const key=(r:any)=>`${r._type}:${r.id}`; const exportPdf=async(explicit?:Selection[])=>{const targets:Selection[]=explicit || rows.filter((r:any)=>selected.includes(key(r))).map((r:any)=>({type:r._type,id:r.id}));if(!targets.length)return;setBusy(true);try{for(let offset=0;offset<targets.length;offset+=40){const result=await getFilterReportPackets(targets.slice(offset,offset+40));if(!result.success)throw new Error(result.error);const packetRows=[...(result.early||[]).map((r:any)=>({...r,_type:'early'})),...(result.extraordinary||[]).map((r:any)=>({...r,_type:'extraordinary'}))];const doc=new jsPDF();for(let i=0;i<packetRows.length;i++){if(i)doc.addPage();await drawRecord(doc,packetRows[i],result.institution,result.urls);}doc.save(`bitacoras-filtro${targets.length>40?`-parte-${offset/40+1}`:''}.pdf`);}toast({title:'PDF generado',description:`${targets.length} expediente(s) exportados.`});}catch(e){toast({variant:'destructive',title:'No se pudo generar el PDF',description:e instanceof Error?e.message:'Error inesperado'});}finally{setBusy(false);}};
  return <div className="space-y-6"><div><h1 className="flex items-center gap-2 text-3xl font-bold text-primary"><FileText />Reportes de entregas</h1><p className="text-muted-foreground">Consulta, selecciona e imprime salidas anticipadas y entregas extraordinarias con sus evidencias.</p></div><Card><CardHeader><CardTitle>Expedientes</CardTitle><CardDescription>Por protección de datos, cada exportación queda registrada en auditoría. Los lotes grandes se separan automáticamente.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_220px_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por alumno"/></div><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Ambas bitácoras</SelectItem><SelectItem value="early">Salidas anticipadas</SelectItem><SelectItem value="extraordinary">Entregas extraordinarias</SelectItem></SelectContent></Select><Button disabled={busy||!selected.length} onClick={() => void exportPdf()}><Download className="mr-2 h-4 w-4"/>{busy?'Preparando…':`Descargar ${selected.length}`}</Button></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={rows.length>0&&rows.every((r:any)=>selected.includes(key(r)))} onCheckedChange={v=>setSelected(v?rows.map(key):[])}/>Seleccionar todos los resultados visibles</label><div className="space-y-2">{rows.map((r:any)=><label key={key(r)} className="flex items-center gap-3 rounded-lg border p-3 hover:bg-muted/40"><Checkbox checked={selected.includes(key(r))} onCheckedChange={v=>setSelected(s=>v?[...new Set([...s,key(r)])]:s.filter(x=>x!==key(r)))}/><span className="flex-1"><b>{r.student_name}</b><span className="block text-xs text-muted-foreground">{r._type==='early'?'Salida anticipada':'Entrega extraordinaria'} · {new Date(r.registered_at).toLocaleString('es-MX')} · {r.reporter_name}</span></span><Button type="button" size="sm" variant="outline" onClick={e=>{e.preventDefault();void exportPdf([{type:r._type,id:r.id}])}}>PDF</Button></label>)}</div></CardContent></Card></div>;
}
async function dataUrl(url?:string){if(!url)return null;try{const response=await fetch(url);if(!response.ok)return null;const blob=await response.blob();const source=URL.createObjectURL(blob);return await new Promise<string>((resolve,reject)=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');const scale=Math.min(1,1400/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d',{alpha:false});if(!context){URL.revokeObjectURL(source);return reject(new Error('canvas'));}context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(source);resolve(canvas.toDataURL('image/jpeg',.82));};image.onerror=()=>{URL.revokeObjectURL(source);reject(new Error('image'));};image.src=source;});}catch{return null;}}

function addContainedImage(doc:jsPDF,image:string,x:number,y:number,width:number,height:number){try{const properties=doc.getImageProperties(image);const scale=Math.min(width/properties.width,height/properties.height);const w=properties.width*scale,h=properties.height*scale;doc.addImage(image,'JPEG',x+(width-w)/2,y+(height-h)/2,w,h,undefined,'FAST');return true;}catch{return false;}}

function enumLabel(value:unknown){const labels:Record<string,string>={madre:'Madre',padre:'Padre',tutor:'Tutor(a)',abuelo:'Abuelo(a)',hermano:'Hermano(a)',familiar_autorizado:'Familiar autorizado',otro:'Otro',whatsapp:'WhatsApp',llamada:'Llamada telefónica',sms:'Mensaje de texto',presencial:'Comunicación presencial',cita_medica:'Cita médica',malestar:'Enfermedad o malestar',asunto_familiar:'Asunto familiar',salida_autorizada:'Salida anticipada autorizada',cambio_transporte:'Cambio de transporte',entregado:'Entregado',rechazado:'Rechazado',cancelado:'Cancelado',familiar:'Familiar',persona_confianza:'Persona de confianza',transportista:'Transportista',personal_medico:'Personal médico',autoridad:'Autoridad',videollamada:'Videollamada',correo:'Correo registrado',documento:'Documento firmado',verified:'Verificada',pending:'Pendiente',approved:'Aprobado'};const key=String(value||'');return labels[key]||key||'—';}

function drawCell(doc:jsPDF,label:string,value:unknown,x:number,y:number,width:number,height:number,color:[number,number,number],alternate:boolean){doc.setFillColor(...(alternate?[247,249,252] as [number,number,number]:[255,255,255] as [number,number,number]));doc.setDrawColor(220,226,234);doc.roundedRect(x,y,width,height,1.2,1.2,'FD');doc.setTextColor(...color);doc.setFont('helvetica','bold');doc.setFontSize(6.8);doc.text(label.toUpperCase(),x+3,y+3.7);doc.setTextColor(31,41,55);doc.setFont('helvetica','normal');doc.setFontSize(8);const lines=doc.splitTextToSize(String(value||'—'),width-6).slice(0,2);doc.text(lines,x+3,y+7.3);}

async function drawRecord(doc:jsPDF,row:any,institution:any,urls:Record<string,string>){
  const color=hex(institution.color_primario||'#0f766e');const pale=mixWithWhite(color,.9);const name=institution.nombre_completo||institution.nombre_corto||'Institución';
  doc.setFillColor(...color);doc.rect(0,0,210,28,'F');
  const logo=await dataUrl(institution.logo_url);if(logo){doc.setFillColor(255,255,255);doc.roundedRect(12,4,20,20,2,2,'F');addContainedImage(doc,logo,14,6,16,16);}else{doc.setFillColor(255,255,255);doc.circle(22,14,9,'F');doc.setTextColor(...color);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(String(name).slice(0,2).toUpperCase(),22,17,{align:'center'});}
  doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(String(name),38,12);doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text('EXPEDIENTE CONFIDENCIAL · CONTROL DE FILTRO',38,18);const contact=[institution.telefono_contacto,institution.correo_contacto].filter(Boolean).join(' · ');if(contact)doc.text(String(contact).slice(0,92),38,23);
  doc.setTextColor(20,30,45);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(row._type==='early'?'Bitácora de salida anticipada':'Entrega a persona extraordinaria',12,38);doc.setFontSize(7);doc.setTextColor(90,100,115);doc.text(`FOLIO ${String(row.id).toUpperCase()}`,198,38,{align:'right'});
  doc.setFillColor(...pale);doc.setDrawColor(...color);doc.roundedRect(12,42,186,15,2,2,'FD');doc.setTextColor(...color);doc.setFontSize(6.8);doc.text('ALUMNO',16,47);doc.setTextColor(20,30,45);doc.setFontSize(11);doc.text(String(row.student_name||'—'),16,53);doc.setFontSize(8);doc.text(`${row.level_name||'—'} · ${row.grade_name||'—'} · ${row.group_name||'—'}`,194,52,{align:'right'});
  const fields=row._type==='early'?[['Fecha y hora',fmt(row.departed_at)],['Persona que retira',row.pickup_person_name],['Parentesco',`${enumLabel(row.relationship)}${row.relationship_other?` · ${row.relationship_other}`:''}`],['¿Quién notificó?',enumLabel(row.notified_party)],['Medio de notificación',enumLabel(row.notification_method)],['Personal notificado',row.notified_staff_name],['Motivo',`${enumLabel(row.departure_reason)}${row.departure_reason_other?` · ${row.departure_reason_other}`:''}`],['Docente que entrega',row.delivering_teacher_name]]:[['Fecha y hora',fmt(row.departed_at||row.registered_at)],['Persona que retira',row.pickup_person_name],['Relación',enumLabel(row.pickup_relationship)],['Autorización',`${enumLabel(row.authorization_method)} · ${row.authorizer_name||'—'}`],['Consentimiento',enumLabel(row.consent_status)],['Resolución',enumLabel(row.status)],['Docente que entrega',row.delivering_teacher_name],['Personal que registra',row.reporter_name]];
  for(let i=0;i<fields.length;i+=2){const y=61+(i/2)*12;drawCell(doc,fields[i][0],fields[i][1],12,y,91,10,color,(i/2)%2===1);drawCell(doc,fields[i+1][0],fields[i+1][1],107,y,91,10,color,(i/2)%2===1);}
  const observations=row._type==='early'?row.description:row.final_observations;doc.setFillColor(250,251,253);doc.setDrawColor(220,226,234);doc.roundedRect(12,111,186,18,1.5,1.5,'FD');doc.setTextColor(...color);doc.setFont('helvetica','bold');doc.setFontSize(7);doc.text('DESCRIPCIÓN Y OBSERVACIONES',16,116);doc.setTextColor(40,48,62);doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text(doc.splitTextToSize(String(observations||'Sin observaciones.'),178).slice(0,3),16,121);
  doc.setTextColor(20,30,45);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Evidencias fotográficas',12,137);
  const photos=row._type==='early'?[['Persona que retira',row.pickup_person_photo_path],['Entrega final',row.final_handover_photo_path]]:[['Persona que retira',row.pickup_person_photo_path],['Entrega final',row.final_handover_photo_path]];
  for(let i=0;i<2;i++){const x=i===0?12:107;doc.setFillColor(247,249,252);doc.setDrawColor(220,226,234);doc.roundedRect(x,141,91,58,2,2,'FD');doc.setTextColor(60,70,85);doc.setFontSize(7);doc.text(photos[i][0],x+4,147);const path=photos[i][1];const image=path&&urls[path]?await dataUrl(urls[path]):null;if(image)addContainedImage(doc,image,x+4,150,83,45);else{doc.setTextColor(150,158,170);doc.text('Sin imagen disponible',x+45.5,174,{align:'center'});}}
  doc.setFillColor(...pale);doc.setDrawColor(...color);doc.roundedRect(12,208,186,60,2,2,'FD');doc.setTextColor(...color);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text('Firma de la persona que recibe al alumno',18,218);doc.setTextColor(95,105,118);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text('La firma forma parte del expediente digital verificado.',18,224);const signaturePath=row.pickup_signature_path;const signature=signaturePath&&urls[signaturePath]?await dataUrl(urls[signaturePath]):null;if(signature)addContainedImage(doc,signature,55,227,100,31);doc.setDrawColor(120,130,145);doc.line(50,260,160,260);doc.setFontSize(7);doc.text(String(row.pickup_person_name||'Persona que recibe'),105,265,{align:'center'});
  doc.setDrawColor(...color);doc.line(12,280,198,280);doc.setTextColor(95,105,118);doc.setFontSize(6.5);doc.text(`Documento generado ${new Date().toLocaleString('es-MX')} · Registro protegido por la institución`,12,285);doc.text('Página 1 de 1',198,285,{align:'right'});
}
function fmt(v:string){return v?new Date(v).toLocaleString('es-MX'):'—';} function hex(value:string):[number,number,number]{const v=value.replace('#','');return v.length===6?[parseInt(v.slice(0,2),16),parseInt(v.slice(2,4),16),parseInt(v.slice(4,6),16)]:[15,118,110];} function mixWithWhite(color:[number,number,number],ratio:number):[number,number,number]{return color.map((channel)=>Math.round(channel+(255-channel)*ratio)) as [number,number,number];}
