-- Eliminar únicamente el índice redundante de cada par detectado por Advisor.
drop index if exists public.idx_abonos_pago_pago_alumno_id_fk;
drop index if exists public.idx_abonos_pago_tenant_id_fk;
drop index if exists public.idx_acreditaciones_alumnos_tenant_id_fk;
drop index if exists public.idx_agrupaciones_profesor_tenant_id_fk;
drop index if exists public.idx_ai_alumno_daily_messages_tenant_id_fk;
drop index if exists public.idx_ai_daily_web_searches_tenant_id_fk;
drop index if exists public.idx_ai_red_list_alerts_tenant_id_fk;
drop index if exists public.idx_ai_session_categories_tenant_id_fk;
drop index if exists public.idx_ai_token_usage_tenant_id_fk;
drop index if exists public.idx_ai_usage_log_tenant_id_fk;
drop index if exists public.idx_alumno_chat_history_tenant_id_fk;
drop index if exists public.idx_asignaciones_profesor_profesor_id_fk;
drop index if exists public.idx_asignaciones_profesor_tenant_id_fk;
drop index if exists public.idx_aspirantes_tenant_id_fk;
drop index if exists public.idx_auditoria_tenant_id_fk;
drop index if exists public.idx_carreras_tenant_id_fk;
drop index if exists public.idx_config_credenciales_tenant_id_fk;
drop index if exists public.idx_config_cuotas_servicio_tenant_id_fk;
drop index if exists public.idx_configuracion_sistema_tenant_id_fk;
drop index if exists public.idx_credenciales_autorizadas_tenant_id_fk;
drop index if exists public.idx_ejercicios_tenant_id_fk;
drop index if exists public.idx_fechas_evaluacion_tenant_id_fk;
drop index if exists public.idx_grados_tenant_id_fk;
drop index if exists public.idx_grupo_materias_tenant_id_fk;
drop index if exists public.idx_grupos_tenant_id_fk;
drop index if exists public.idx_inscripciones_alumno_alumno_id_fk;
drop index if exists public.inscripciones_alumno_tenant_id_idx;
drop index if exists public.material_apoyo_tenant_id_idx;
drop index if exists public.materias_tenant_id_idx;
drop index if exists public.mensajes_acreditacion_tenant_id_idx;
drop index if exists public.mensajes_clases_tenant_id_idx;
drop index if exists public.mensajes_clases_vistos_tenant_id_idx;
drop index if exists public.mensajes_contacto_tenant_id_idx;
drop index if exists public.mensajes_internos_tenant_id_idx;
drop index if exists public.mensajes_vistos_tenant_id_idx;
drop index if exists public.niveles_tenant_id_idx;
drop index if exists public.notificaciones_tenant_id_idx;
drop index if exists public.pago_de_servicios_tenant_id_idx;
drop index if exists public.pagos_alumno_tenant_id_idx;
drop index if exists public.plan_pagos_tenant_id_idx;
drop index if exists public.profesor_chat_history_tenant_id_idx;
drop index if exists public.idx_profiles_grupo_id_fk;
drop index if exists public.profiles_tenant_id_idx;
drop index if exists public.recursos_tenant_id_idx;
drop index if exists public.resources_tenant_id_idx;
drop index if exists public.resultados_ejercicios_tenant_id_idx;
drop index if exists public.slides_tenant_id_idx;
drop index if exists public.temas_tenant_id_idx;
drop index if exists public.tenant_domains_tenant_id_idx;
drop index if exists public.tenant_provisioning_tenant_id_idx;
drop index if exists public.unidades_tenant_id_idx;
drop index if exists public.video_progreso_alumno_tenant_id_idx;

create index if not exists idx_fechas_evaluacion_materia_id_fk on public.fechas_evaluacion(materia_id);
create index if not exists idx_grupo_materias_materia_id_fk on public.grupo_materias(materia_id);
create index if not exists idx_mensajes_clases_vistos_usuario_id_fk on public.mensajes_clases_vistos(usuario_id);
create index if not exists idx_mensajes_vistos_usuario_id_fk on public.mensajes_vistos(usuario_id);
create index if not exists idx_pagos_alumno_plan_pago_id_fk on public.pagos_alumno(plan_pago_id);
create index if not exists idx_resultados_ejercicios_ejercicio_id_fk on public.resultados_ejercicios(ejercicio_id);
create index if not exists idx_video_progreso_alumno_tema_id_fk on public.video_progreso_alumno(tema_id);
